#!/bin/bash
# usage: icloud-backup [--compare] ~/Backup

set -euo pipefail

main() {
	case "$1" in
	--help | -h)
		sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' <"$0"
		exit 0
		;;
	--compare)
		compare "$2"
		exit 0
		;;
	'')
		"$0" --help | head -1 >&2
		exit 1
		;;
	*)
		backup "$1/$(date +'%Y-%m-%d') iCloud Backup.tar"
		exit 0
		;;
	esac
}

backup() {
	tar -rf "$1" -C "$HOME" "Desktop"
	tar -rf "$1" -C "$HOME" "Documents"
	tar -rf "$1" -C "$HOME/Library" "Mobile Documents"
	tar -rf "$1" -C "$HOME/Library" "Keychains"

	export_notes "/tmp/Notes"
	tar -rf "$1" -C "/tmp" "Notes"

	gzip -f "$1"
}

export_notes() {
	rm -rf "$1"
	mkdir "$1"
	while IFS= read -r -d '' status && IFS= read -r -d '' name && IFS= read -r -d '' body; do
		safe_name="$(echo "$name" | sed -e 's/[^A-Za-z0-9 ._-]//g')"
		echo "$body" >"$1/$safe_name.html"
	done < <(print_notes)
	[ "$status" = $'\nOK\n' ]
}

print_notes() {
	osascript 2>&1 <<'AS'
  tell application "Notes"
    set myDelim to character id 0
    repeat with theNote in notes
      log myDelim & (get name of theNote) & myDelim & (get body of theNote) & myDelim
    end repeat
    log "OK"
  end tell
AS
}

compare() {
	rm -rf /tmp/icloud-backup
	mkdir -p /tmp/icloud-backup
	pushd /tmp/icloud-backup >/dev/null

	tar --no-same-permissions -xzf "$1"

	comm -3 <(md5sum "Desktop/" | sort) <(md5sum "$HOME/Desktop" | sort)
	comm -3 <(md5sum "Documents/" | sort) <(md5sum "$HOME/Documents" | sort)
	comm -3 <(md5sum "Mobile Documents/" | sort) <(md5sum "$HOME/Library/Mobile Documents" | sort)
}

md5sum() {
	pushd "$1" >/dev/null
	find . -type f -print0 | while IFS= read -rd '' path; do
		md5 -r "$path"
	done
	popd >/dev/null
}

main "$@"
