#!/bin/bash
# Usage: icloud-backup ~/Backup

set -e

DIR="$1"

case "$DIR" in
--help | -h )
  sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
  exit 0
  ;;
'' )
  "$0" --help | head -1 >&2
  exit 1
  ;;
esac

TAR="$DIR/$(date +'%Y-%m-%d') iCloud Backup.tar"

rm -rf /tmp/Notes
mkdir /tmp/Notes

osascript -l JavaScript <<'JS'
function run() {
  const Notes = Application("Notes");
  for (const note of Notes.notes()) {
    const str = $.NSString.alloc.initWithUTF8String(note.body());
    str.writeToFileAtomicallyEncodingError(
      `/tmp/Notes/${note.name()}.html`,
      true,
      $.NSUTF8StringEncoding,
      null
    );
  }
}
JS

set -x
mkdir -p "$DIR"
tar -v -r -f "$TAR" -C "$HOME" "Desktop"
tar -v -r -f "$TAR" -C "$HOME" "Documents"
tar -v -r -f "$TAR" -C "$HOME/Library" "Mobile Documents"
tar -v -r -f "$TAR" -C "$HOME/Library" "Keychains"
tar -v -r -f "$TAR" -C "/tmp" "Notes"
gzip -f "$TAR"
