#!/bin/bash
# Usage: icloud-backup ~/Backup

set -e

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(readlink "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

DIR="$1"

case "$DIR" in
--help | -h )
  sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
  exit 0
  ;;
'' )
  "$0" --help | head -1 >&2
  exit 1
  ;;
esac

TAR="$DIR/$(date +'%Y-%m-%d') iCloud Backup.tar"

rm -rf /tmp/Backup
mkdir -p /tmp/Backup/Notes
export-notes /tmp/Backup/Notes

set -x
mkdir -p "$DIR"
tar -v -r -f "$TAR" -C "$HOME" "Desktop"
tar -v -r -f "$TAR" -C "$HOME" "Documents"
tar -v -r -f "$TAR" -C "$HOME/Library" "Mobile Documents"
tar -v -r -f "$TAR" -C "$HOME/Library" "Keychains"
tar -v -r -f "$TAR" -C "/tmp/Backup" "Notes"
gzip -f "$TAR"
