name: Lint

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Check files
        run: shellcheck icloud-backup

  shfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: Check files
        run: shfmt -d .
